---
- import_role:
    name: dokku_bot.ansible_dokku
  vars:
    dokku_skip_key_file: 'true'
    dokku_version: 0.18.2
    dokku_vhost_enable: 'true'
    dokku_web_config: 'false'
    herokuish_version: 0.5.3
    plugn_version: 0.3.2
    sshcommand_version: 0.8.0
    dokku_users:
      - name: richard
        username: richard
        ssh_key: "{{ lookup('file', controller_key) }}"

- name: apps:create {{ application }}
  dokku_app:
    app: "{{ application }}"
    state: present
  tags:
    - dokku

- name: domains:add {{ application }} {{ domain }}
  dokku_domains:
    app: "{{ application }}"
    domains:
      - "{{ domain }}"
    state: present
  tags:
    - dokku

- import_tasks: rails.yml
- import_tasks: ssl.yml
