---
- import_role:
    name: dokku_bot.ansible_dokku

# Rails specific configuration
#
- name: config:set {{ dokku.application }} RAILS_ENV= {{ rails_env }} RAILS_MASTER_KEY=XXXX RAILS_SERVE_STATIC_FILES=true
  dokku_config:
    app: "{{ dokku.application }}"
    config:
      RAILS_ENV: "{{ rails_env }}"
      RAILS_MASTER_KEY: "{{ lookup('file', rails_master_key )}}"

      # While this is slower than using NGINX Proxy. Dokku doesn't offer that
      # if you need faster static assets than use a CDN (which is faster than
      # NGINX proxy anyway)
      #
      RAILS_SERVE_STATIC_FILES: "true"
  tags:
    - dokku
    - master.key
    - env

- name: config:set {{ dokku.application }} banner mark
  dokku_config:
    app: "{{ dokku.application }}"
    config:
      RACK_DEV_MARK_ENV: "{{ rack_dev_mark_env }}"
  # when: rack_dev_mark_env is defined
  tags:
    - dokku
    - env

- name: config {{ dokku.application }}
  command: dokku config "{{ dokku.application }}"
  register: debug_dokku_config
  tags:
    - never
    - info
    - env

- name: display debug_dokku_config
  debug:
    msg: "{{ debug_dokku_config.stdout_lines }}"
  tags:
    - never
    - info
    - env
