AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - Gemfile
    - Rakefile
    - db/**/*
    - bin/**/*
    - tmp/**/*
    - config/**/*
    - test/**/*
    - node_modules/**/*

# Offense count: 1
# Cop supports --auto-correct.
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 3
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'spec/rails_helper.rb'

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, never
Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'app/channels/application_cable/channel.rb'
    - 'app/channels/application_cable/connection.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/jobs/application_job.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config.ru'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

# Offense count: 47
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true
  Exclude:
    - 'app/mailers/application_mailer.rb'
    - 'config.ru'
    - 'spec/rails_helper.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 130
