source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 2.6.0'

gem 'bootsnap', '>= 1.4.2', require: false
gem 'inline_svg', '~> 1.5.0'
gem 'jbuilder', '~> 2.7'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.3'
gem 'rails', '~> 6.0.0'
gem 'rack-dev-mark', '~> 0.7.0'
gem 'sass-rails', '~> 5'
gem 'sitemap_generator', '~> 6.0.0'
gem 'turbolinks', '5.3.0-beta.1', git: 'https://github.com/turbolinks/turbolinks.git'
gem 'webpacker', '~> 4.0'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'factory_bot_rails'
  gem 'rubocop', '~> 0.74.0', require: false
end

group :development do
  gem 'bundler-audit'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'solargraph'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
